#pragma once

#include <cstdint>

#include "pruftnet/parsing/registry.hpp"

namespace pruftnet::parsing::internal {

struct Ipv4DissectorState {
  FieldId packet;
  FieldId version;
  FieldId header_length;
  FieldId dscp_ecn;
  FieldId total_length;
  FieldId identification;
  FieldId flags;
  FieldId reserved_flag;
  FieldId dont_fragment;
  FieldId more_fragments;
  FieldId fragment_offset_encoded;
  FieldId fragment_offset;
  FieldId reassembled;
  FieldId reassembled_length;
  FieldId reassembled_fragment_count;
  FieldId fragment_overlap;
  FieldId ttl;
  FieldId protocol;
  FieldId checksum;
  FieldId source;
  FieldId destination;
  FieldId options;
};

struct UdpDissectorState {
  FieldId datagram;
  FieldId source_port;
  FieldId destination_port;
  FieldId length;
  FieldId checksum;
  FieldId payload;
};

struct TcpDissectorState {
  FieldId segment;
  FieldId source_port;
  FieldId destination_port;
  FieldId sequence_number;
  FieldId acknowledgment_number;
  FieldId header_length;
  FieldId reserved;
  FieldId flags;
  FieldId window;
  FieldId checksum;
  FieldId urgent_pointer;
  FieldId options;
  FieldId payload;
  FieldId reassembled;
  FieldId reassembled_length;
  FieldId reassembled_segment_count;
  FieldId reassembly_overlap;
  FieldId reassembly_conflict;
};

struct ArpDissectorState {
  FieldId packet;
  FieldId reverse_packet;
  FieldId inverse_packet;
  FieldId hardware_type;
  FieldId protocol_type;
  FieldId hardware_length;
  FieldId protocol_length;
  FieldId operation;
  FieldId sender_hardware;
  FieldId sender_protocol;
  FieldId target_hardware;
  FieldId target_protocol;
};

struct Ipv6DissectorState {
  FieldId packet;
  FieldId version;
  FieldId traffic_class;
  FieldId flow_label;
  FieldId payload_length;
  FieldId next_header;
  FieldId hop_limit;
  FieldId source;
  FieldId destination;
  FieldId extension;
  FieldId extension_next_header;
  FieldId extension_length;
  FieldId extension_type;
  FieldId extension_data;
  FieldId fragment_offset_encoded;
  FieldId fragment_offset;
  FieldId fragment_reserved_octet;
  FieldId fragment_reserved;
  FieldId fragment_more;
  FieldId fragment_atomic;
  FieldId fragment_identification;
  FieldId reassembled;
  FieldId reassembled_length;
  FieldId reassembled_fragment_count;
  FieldId fragment_overlap;
};

struct IcmpExtensionDissectorState {
  FieldId structure;
  FieldId version;
  FieldId reserved;
  FieldId checksum;
  FieldId checksum_valid;
  FieldId object;
  FieldId object_length;
  FieldId object_class;
  FieldId object_ctype;
  FieldId object_data;
  FieldId mpls_entry;
  FieldId mpls_label;
  FieldId mpls_traffic_class;
  FieldId mpls_bottom_of_stack;
  FieldId mpls_ttl;
};

enum class DnsFlavor : std::uint8_t {
  Dns,
  Mdns,
  Llmnr,
};

struct DnsDissectorState {
  FieldId message;
  FieldId tcp_stream;
  FieldId tcp_length;
  FieldId id;
  FieldId flags;
  FieldId response;
  FieldId opcode;
  FieldId authoritative;
  FieldId truncated;
  FieldId recursion_desired;
  FieldId recursion_available;
  FieldId authenticated_data;
  FieldId checking_disabled;
  FieldId rcode;
  FieldId conflict;
  FieldId tentative;
  FieldId question_count;
  FieldId answer_count;
  FieldId authority_count;
  FieldId additional_count;
  FieldId question;
  FieldId question_name;
  FieldId question_type;
  FieldId question_class;
  FieldId unicast_response;
  FieldId record;
  FieldId record_section;
  FieldId record_name;
  FieldId record_type;
  FieldId record_class;
  FieldId cache_flush;
  FieldId ttl;
  FieldId record_length;
  FieldId record_data;
  FieldId address;
  FieldId target;
  FieldId preference;
  FieldId priority;
  FieldId weight;
  FieldId port;
  FieldId text;
  FieldId soa_mname;
  FieldId soa_rname;
  FieldId soa_serial;
  FieldId soa_refresh;
  FieldId soa_retry;
  FieldId soa_expire;
  FieldId soa_minimum;
  FieldId edns_udp_payload_size;
  FieldId edns_extended_rcode;
  FieldId edns_version;
  FieldId edns_flags;
  FieldId edns_option;
  FieldId edns_option_code;
  FieldId edns_option_length;
  FieldId edns_option_data;
  FieldId trailing;
  DnsFlavor flavor;
  bool tcp;
};

struct HttpDissectorState {
  FieldId stream;
  FieldId message;
  FieldId request;
  FieldId response;
  FieldId request_line;
  FieldId response_line;
  FieldId method;
  FieldId request_target;
  FieldId version;
  FieldId status_code;
  FieldId reason_phrase;
  FieldId header;
  FieldId header_name;
  FieldId header_value;
  FieldId host;
  FieldId user_agent;
  FieldId content_type;
  FieldId content_length;
  FieldId transfer_encoding;
  FieldId connection;
  FieldId body;
  FieldId chunk;
  FieldId chunk_size;
  FieldId chunk_extension;
  FieldId chunk_data;
  FieldId trailing;
};

struct TlsDissectorState {
  FieldId stream;
  FieldId record;
  FieldId content_type;
  FieldId legacy_version;
  FieldId record_length;
  FieldId record_payload;
  FieldId alert;
  FieldId alert_level;
  FieldId alert_description;
  FieldId change_cipher_spec;
  FieldId heartbeat;
  FieldId heartbeat_type;
  FieldId heartbeat_length;
  FieldId heartbeat_payload;
  FieldId handshake;
  FieldId handshake_type;
  FieldId handshake_length;
  FieldId handshake_version;
  FieldId random;
  FieldId session_id;
  FieldId cipher_suites_length;
  FieldId cipher_suite;
  FieldId compression_methods_length;
  FieldId compression_method;
  FieldId extensions_length;
  FieldId extension;
  FieldId extension_type;
  FieldId extension_length;
  FieldId extension_data;
  FieldId server_name_type;
  FieldId server_name;
  FieldId alpn;
  FieldId supported_group;
  FieldId signature_algorithm;
  FieldId supported_version;
  FieldId handshake_body;
  FieldId handshake_reassembled;
  FieldId trailing;
};

struct QuicDissectorState {
  FieldId packet;
  FieldId packet_type;
  FieldId packet_length;
  FieldId coalesced_index;
  FieldId header_form;
  FieldId fixed_bit;
  FieldId long_packet_type_bits;
  FieldId type_specific_bits;
  FieldId version;
  FieldId destination_connection_id_length;
  FieldId destination_connection_id;
  FieldId source_connection_id_length;
  FieldId source_connection_id;
  FieldId token_length;
  FieldId token;
  FieldId length;
  FieldId protected_payload;
  FieldId supported_version;
  FieldId retry_token;
  FieldId retry_integrity_tag;
  FieldId spin_bit;
  FieldId short_protected_bits;
  FieldId version_specific_data;
};

struct DhcpDissectorState {
  FieldId message;
  FieldId operation;
  FieldId hardware_type;
  FieldId hardware_length;
  FieldId hops;
  FieldId transaction_id;
  FieldId seconds;
  FieldId flags;
  FieldId broadcast;
  FieldId client_address;
  FieldId your_address;
  FieldId server_address;
  FieldId relay_address;
  FieldId client_hardware_address;
  FieldId client_hardware_padding;
  FieldId server_name;
  FieldId boot_file;
  FieldId magic_cookie;
  FieldId option;
  FieldId option_code;
  FieldId option_length;
  FieldId option_data;
  FieldId message_type;
  FieldId subnet_mask;
  FieldId router;
  FieldId dns_server;
  FieldId host_name;
  FieldId domain_name;
  FieldId requested_address;
  FieldId lease_time;
  FieldId server_identifier;
  FieldId parameter_request;
  FieldId maximum_message_size;
  FieldId renewal_time;
  FieldId rebinding_time;
  FieldId vendor_class;
  FieldId client_identifier;
  FieldId overload;
  FieldId relay_suboption;
  FieldId relay_suboption_code;
  FieldId relay_suboption_length;
  FieldId relay_suboption_data;
  FieldId end;
  FieldId padding;
  FieldId trailing;
};

struct Dhcpv6DissectorState {
  FieldId message;
  FieldId message_type;
  FieldId transaction_id;
  FieldId hop_count;
  FieldId link_address;
  FieldId peer_address;
  FieldId option;
  FieldId option_code;
  FieldId option_length;
  FieldId option_data;
  FieldId duid;
  FieldId duid_type;
  FieldId duid_hardware_type;
  FieldId duid_time;
  FieldId duid_enterprise;
  FieldId duid_identifier;
  FieldId iaid;
  FieldId t1;
  FieldId t2;
  FieldId address;
  FieldId preferred_lifetime;
  FieldId valid_lifetime;
  FieldId prefix_length;
  FieldId prefix;
  FieldId requested_option;
  FieldId preference;
  FieldId elapsed_time;
  FieldId status_code;
  FieldId status_message;
  FieldId dns_server;
  FieldId domain_search;
  FieldId relay_message;
  FieldId interface_id;
  FieldId rapid_commit;
  FieldId information_refresh_time;
  FieldId sol_max_rt;
  FieldId inf_max_rt;
  FieldId trailing;
};

struct IgmpDissectorState {
  FieldId packet;
  FieldId type;
  FieldId version;
  FieldId max_response_code;
  FieldId max_response_time;
  FieldId checksum;
  FieldId checksum_valid;
  FieldId group_address;
  FieldId reserved;
  FieldId suppress;
  FieldId qrv;
  FieldId qqic;
  FieldId query_interval;
  FieldId source_count;
  FieldId source_address;
  FieldId record_count;
  FieldId record;
  FieldId record_type;
  FieldId aux_data_length;
  FieldId record_source_count;
  FieldId record_multicast_address;
  FieldId record_source_address;
  FieldId aux_data;
  FieldId trailing;
};

struct MldDissectorState {
  FieldId message;
  FieldId version;
  FieldId maximum_response_code;
  FieldId maximum_response_delay;
  FieldId reserved;
  FieldId multicast_address;
  FieldId flags;
  FieldId suppress;
  FieldId qrv;
  FieldId qqic;
  FieldId query_interval;
  FieldId source_count;
  FieldId source_address;
  FieldId record_count;
  FieldId record;
  FieldId record_type;
  FieldId aux_data_length;
  FieldId record_source_count;
  FieldId record_multicast_address;
  FieldId record_source_address;
  FieldId aux_data;
  FieldId trailing;
};

struct NtpDissectorState {
  FieldId message;
  FieldId flags;
  FieldId leap_indicator;
  FieldId version;
  FieldId mode;
  FieldId stratum;
  FieldId poll;
  FieldId precision;
  FieldId root_delay;
  FieldId root_dispersion;
  FieldId reference_id;
  FieldId reference_timestamp;
  FieldId origin_timestamp;
  FieldId receive_timestamp;
  FieldId transmit_timestamp;
  FieldId extension;
  FieldId extension_type;
  FieldId extension_length;
  FieldId extension_value;
  FieldId key_id;
  FieldId digest;
  FieldId control_flags;
  FieldId control_response;
  FieldId control_error;
  FieldId control_more;
  FieldId control_opcode;
  FieldId control_sequence;
  FieldId control_status;
  FieldId control_association_id;
  FieldId control_offset;
  FieldId control_count;
  FieldId control_data;
  FieldId private_flags;
  FieldId private_response;
  FieldId private_more;
  FieldId private_auth;
  FieldId private_sequence;
  FieldId private_implementation;
  FieldId private_request_code;
  FieldId private_error_code;
  FieldId private_item_count;
  FieldId private_item_size;
  FieldId private_data;
  FieldId trailing;
};

struct GreDissectorState {
  FieldId packet;
  FieldId flags;
  FieldId checksum_present;
  FieldId routing_present;
  FieldId key_present;
  FieldId sequence_present;
  FieldId strict_source_route;
  FieldId recursion_control;
  FieldId acknowledgment_present;
  FieldId reserved;
  FieldId version;
  FieldId protocol_type;
  FieldId checksum;
  FieldId checksum_valid;
  FieldId offset;
  FieldId key;
  FieldId sequence_number;
  FieldId payload_length;
  FieldId call_id;
  FieldId acknowledgment_number;
  FieldId routing_entry;
  FieldId routing_address_family;
  FieldId routing_offset;
  FieldId routing_length;
  FieldId routing_information;
};

enum class VxlanFlavor : std::uint8_t {
  Standard,
  Gpe,
};

struct VxlanDissectorState {
  FieldId packet;
  FieldId flags;
  FieldId version;
  FieldId instance;
  FieldId next_protocol_present;
  FieldId oam;
  FieldId group_policy_present;
  FieldId vni_present;
  FieldId dont_learn;
  FieldId policy_applied;
  FieldId reserved_flags;
  FieldId group_policy_id;
  FieldId reserved_16;
  FieldId next_protocol;
  FieldId vni;
  FieldId reserved_8;
  VxlanFlavor flavor;
};

struct GeneveDissectorState {
  FieldId packet;
  FieldId version;
  FieldId option_length;
  FieldId flags;
  FieldId oam;
  FieldId critical_options;
  FieldId reserved_flags;
  FieldId protocol_type;
  FieldId vni;
  FieldId reserved;
  FieldId option;
  FieldId option_class;
  FieldId option_type;
  FieldId option_critical;
  FieldId option_reserved;
  FieldId option_data_length;
  FieldId option_data;
};

struct MplsDissectorState {
  FieldId packet;
  FieldId entry;
  FieldId label;
  FieldId traffic_class;
  FieldId bottom_of_stack;
  FieldId ttl;
  FieldId payload_protocol;
  FieldId gach;
  FieldId gach_channel_indicator;
  FieldId gach_version;
  FieldId gach_reserved;
  FieldId gach_channel_type;
  FieldId payload;
};

struct Icmpv4DissectorState {
  FieldId message;
  FieldId type;
  FieldId code;
  FieldId checksum;
  FieldId identifier;
  FieldId sequence;
  FieldId gateway;
  FieldId pointer;
  FieldId mtu;
  FieldId body;
  FieldId quoted;
  FieldId original_datagram_length_words;
  FieldId original_datagram_length;
  FieldId extended_sequence;
  FieldId extended_flags;
  FieldId originate_timestamp;
  FieldId receive_timestamp;
  FieldId transmit_timestamp;
  FieldId address_mask;
  FieldId router_address_count;
  FieldId router_entry_size;
  FieldId router_lifetime;
  FieldId router_entry;
  FieldId router_address;
  FieldId router_preference;
  IcmpExtensionDissectorState extension;
};

struct Icmpv6DissectorState {
  FieldId message;
  FieldId type;
  FieldId code;
  FieldId checksum;
  FieldId informational;
  FieldId identifier;
  FieldId sequence;
  FieldId mtu;
  FieldId pointer;
  FieldId target;
  FieldId destination;
  FieldId flags;
  FieldId current_hop_limit;
  FieldId router_lifetime;
  FieldId reachable_time;
  FieldId retrans_timer;
  FieldId body;
  FieldId quoted;
  FieldId option;
  FieldId option_type;
  FieldId option_length;
  FieldId option_body;
  FieldId redirected_packet;
  FieldId link_layer_address;
  FieldId prefix_length;
  FieldId prefix_flags;
  FieldId valid_lifetime;
  FieldId preferred_lifetime;
  FieldId prefix;
  FieldId original_datagram_length_words;
  FieldId original_datagram_length;
  FieldId extended_sequence;
  FieldId extended_flags;
  IcmpExtensionDissectorState extension;
  MldDissectorState mld;
};

} // namespace pruftnet::parsing::internal
