#include "parsing/catalog/catalog_sections.hpp"

#include <string_view>

#include "parsing/dissectors/application/dhcp_dissector.hpp"
#include "parsing/dissectors/application/dhcpv6_dissector.hpp"
#include "parsing/dissectors/application/dns_dissector.hpp"
#include "parsing/dissectors/application/http_dissector.hpp"
#include "parsing/dissectors/application/ntp_dissector.hpp"
#include "parsing/dissectors/application/quic_dissector.hpp"
#include "parsing/dissectors/application/tls_dissector.hpp"

namespace pruftnet::parsing::internal {
namespace {

DnsDissectorState dns_state(const CatalogRegistrar &registrar,
                            std::string_view message_key, DnsFlavor flavor,
                            bool tcp) {
  return {
      registrar.field(message_key),
      registrar.field("dns.tcp_stream"),
      registrar.field("dns.tcp_length"),
      registrar.field("dns.id"),
      registrar.field("dns.flags"),
      registrar.field("dns.response"),
      registrar.field("dns.opcode"),
      registrar.field("dns.authoritative"),
      registrar.field("dns.truncated"),
      registrar.field("dns.recursion_desired"),
      registrar.field("dns.recursion_available"),
      registrar.field("dns.authenticated_data"),
      registrar.field("dns.checking_disabled"),
      registrar.field("dns.rcode"),
      registrar.field("llmnr.conflict"),
      registrar.field("llmnr.tentative"),
      registrar.field("dns.question_count"),
      registrar.field("dns.answer_count"),
      registrar.field("dns.authority_count"),
      registrar.field("dns.additional_count"),
      registrar.field("dns.question"),
      registrar.field("dns.question.name"),
      registrar.field("dns.question.type"),
      registrar.field("dns.question.class"),
      registrar.field("mdns.question.unicast_response"),
      registrar.field("dns.record"),
      registrar.field("dns.record.section"),
      registrar.field("dns.record.name"),
      registrar.field("dns.record.type"),
      registrar.field("dns.record.class"),
      registrar.field("mdns.record.cache_flush"),
      registrar.field("dns.record.ttl"),
      registrar.field("dns.record.length"),
      registrar.field("dns.record.data"),
      registrar.field("dns.address"),
      registrar.field("dns.target"),
      registrar.field("dns.preference"),
      registrar.field("dns.priority"),
      registrar.field("dns.weight"),
      registrar.field("dns.port"),
      registrar.field("dns.text"),
      registrar.field("dns.soa.mname"),
      registrar.field("dns.soa.rname"),
      registrar.field("dns.soa.serial"),
      registrar.field("dns.soa.refresh"),
      registrar.field("dns.soa.retry"),
      registrar.field("dns.soa.expire"),
      registrar.field("dns.soa.minimum"),
      registrar.field("dns.edns.udp_payload_size"),
      registrar.field("dns.edns.extended_rcode"),
      registrar.field("dns.edns.version"),
      registrar.field("dns.edns.flags"),
      registrar.field("dns.edns.option"),
      registrar.field("dns.edns.option.code"),
      registrar.field("dns.edns.option.length"),
      registrar.field("dns.edns.option.data"),
      registrar.field("dns.trailing"),
      flavor,
      tcp,
  };
}

} // namespace

void register_application_catalog(CatalogRegistrar &registrar) {
  registrar.bind_udp_port(
      53, registrar.add_state(dissect_dns, dns_state(registrar, "dns.message",
                                                     DnsFlavor::Dns, false)));
  registrar.bind_tcp_port(
      53, registrar.add_state(dissect_dns, dns_state(registrar, "dns.message",
                                                     DnsFlavor::Dns, true)));
  registrar.bind_udp_port(
      5353,
      registrar.add_state(dissect_dns, dns_state(registrar, "mdns.message",
                                                 DnsFlavor::Mdns, false)));
  registrar.bind_udp_port(
      5355,
      registrar.add_state(dissect_dns, dns_state(registrar, "llmnr.message",
                                                 DnsFlavor::Llmnr, false)));
  registrar.bind_tcp_port(
      5355,
      registrar.add_state(dissect_dns, dns_state(registrar, "llmnr.message",
                                                 DnsFlavor::Llmnr, true)));

  registrar.bind_tcp_port(
      80, registrar.add_state(dissect_http,
                              HttpDissectorState{
                                  registrar.field("http.stream"),
                                  registrar.field("http.message"),
                                  registrar.field("http.request"),
                                  registrar.field("http.response"),
                                  registrar.field("http.request_line"),
                                  registrar.field("http.response_line"),
                                  registrar.field("http.method"),
                                  registrar.field("http.request_target"),
                                  registrar.field("http.version"),
                                  registrar.field("http.status_code"),
                                  registrar.field("http.reason_phrase"),
                                  registrar.field("http.header"),
                                  registrar.field("http.header.name"),
                                  registrar.field("http.header.value"),
                                  registrar.field("http.host"),
                                  registrar.field("http.user_agent"),
                                  registrar.field("http.content_type"),
                                  registrar.field("http.content_length"),
                                  registrar.field("http.transfer_encoding"),
                                  registrar.field("http.connection"),
                                  registrar.field("http.body"),
                                  registrar.field("http.chunk"),
                                  registrar.field("http.chunk.size"),
                                  registrar.field("http.chunk.extension"),
                                  registrar.field("http.chunk.data"),
                                  registrar.field("http.trailing"),
                              }));

  registrar.bind_tcp_port(
      443, registrar.add_state(
               dissect_tls,
               TlsDissectorState{
                   registrar.field("tls.stream"),
                   registrar.field("tls.record"),
                   registrar.field("tls.content_type"),
                   registrar.field("tls.legacy_version"),
                   registrar.field("tls.length"),
                   registrar.field("tls.record_payload"),
                   registrar.field("tls.alert"),
                   registrar.field("tls.alert.level"),
                   registrar.field("tls.alert.description"),
                   registrar.field("tls.change_cipher_spec"),
                   registrar.field("tls.heartbeat"),
                   registrar.field("tls.heartbeat.type"),
                   registrar.field("tls.heartbeat.length"),
                   registrar.field("tls.heartbeat.payload"),
                   registrar.field("tls.handshake"),
                   registrar.field("tls.handshake.type"),
                   registrar.field("tls.handshake.length"),
                   registrar.field("tls.handshake.version"),
                   registrar.field("tls.handshake.random"),
                   registrar.field("tls.handshake.session_id"),
                   registrar.field("tls.handshake.cipher_suites_length"),
                   registrar.field("tls.handshake.cipher_suite"),
                   registrar.field("tls.handshake.compression_methods_length"),
                   registrar.field("tls.handshake.compression_method"),
                   registrar.field("tls.handshake.extensions_length"),
                   registrar.field("tls.extension"),
                   registrar.field("tls.extension.type"),
                   registrar.field("tls.extension.length"),
                   registrar.field("tls.extension.data"),
                   registrar.field("tls.handshake.server_name_type"),
                   registrar.field("tls.handshake.server_name"),
                   registrar.field("tls.handshake.alpn"),
                   registrar.field("tls.handshake.supported_group"),
                   registrar.field("tls.handshake.signature_algorithm"),
                   registrar.field("tls.handshake.supported_version"),
                   registrar.field("tls.handshake.body"),
                   registrar.field("tls.handshake.reassembled"),
                   registrar.field("tls.trailing"),
               }));

  registrar.bind_udp_port(
      443, registrar.add_state(
               dissect_quic,
               QuicDissectorState{
                   registrar.field("quic.packet"),
                   registrar.field("quic.packet_type"),
                   registrar.field("quic.packet_length"),
                   registrar.field("quic.coalesced_index"),
                   registrar.field("quic.header_form"),
                   registrar.field("quic.fixed_bit"),
                   registrar.field("quic.long_packet_type_bits"),
                   registrar.field("quic.type_specific_bits"),
                   registrar.field("quic.version"),
                   registrar.field("quic.destination_connection_id_length"),
                   registrar.field("quic.destination_connection_id"),
                   registrar.field("quic.source_connection_id_length"),
                   registrar.field("quic.source_connection_id"),
                   registrar.field("quic.token_length"),
                   registrar.field("quic.token"),
                   registrar.field("quic.length"),
                   registrar.field("quic.protected_payload"),
                   registrar.field("quic.supported_version"),
                   registrar.field("quic.retry_token"),
                   registrar.field("quic.retry_integrity_tag"),
                   registrar.field("quic.spin_bit"),
                   registrar.field("quic.short_protected_bits"),
                   registrar.field("quic.version_specific_data"),
               }));

  const auto dhcp_handle = registrar.add_state(
      dissect_dhcp, DhcpDissectorState{
                        registrar.field("dhcp.message"),
                        registrar.field("dhcp.operation"),
                        registrar.field("dhcp.hardware_type"),
                        registrar.field("dhcp.hardware_length"),
                        registrar.field("dhcp.hops"),
                        registrar.field("dhcp.transaction_id"),
                        registrar.field("dhcp.seconds"),
                        registrar.field("dhcp.flags"),
                        registrar.field("dhcp.broadcast"),
                        registrar.field("dhcp.client_address"),
                        registrar.field("dhcp.your_address"),
                        registrar.field("dhcp.server_address"),
                        registrar.field("dhcp.relay_address"),
                        registrar.field("dhcp.client_hardware_address"),
                        registrar.field("dhcp.client_hardware_padding"),
                        registrar.field("dhcp.server_name"),
                        registrar.field("dhcp.boot_file"),
                        registrar.field("dhcp.magic_cookie"),
                        registrar.field("dhcp.option"),
                        registrar.field("dhcp.option.code"),
                        registrar.field("dhcp.option.length"),
                        registrar.field("dhcp.option.data"),
                        registrar.field("dhcp.message_type"),
                        registrar.field("dhcp.subnet_mask"),
                        registrar.field("dhcp.router"),
                        registrar.field("dhcp.dns_server"),
                        registrar.field("dhcp.host_name"),
                        registrar.field("dhcp.domain_name"),
                        registrar.field("dhcp.requested_address"),
                        registrar.field("dhcp.lease_time"),
                        registrar.field("dhcp.server_identifier"),
                        registrar.field("dhcp.parameter_request"),
                        registrar.field("dhcp.maximum_message_size"),
                        registrar.field("dhcp.renewal_time"),
                        registrar.field("dhcp.rebinding_time"),
                        registrar.field("dhcp.vendor_class"),
                        registrar.field("dhcp.client_identifier"),
                        registrar.field("dhcp.overload"),
                        registrar.field("dhcp.relay_suboption"),
                        registrar.field("dhcp.relay_suboption.code"),
                        registrar.field("dhcp.relay_suboption.length"),
                        registrar.field("dhcp.relay_suboption.data"),
                        registrar.field("dhcp.end"),
                        registrar.field("dhcp.padding"),
                        registrar.field("dhcp.trailing"),
                    });
  registrar.bind_udp_port(67, dhcp_handle);
  registrar.bind_udp_port(68, dhcp_handle);

  const auto dhcpv6_handle = registrar.add_state(
      dissect_dhcpv6, Dhcpv6DissectorState{
                          registrar.field("dhcpv6.message"),
                          registrar.field("dhcpv6.message_type"),
                          registrar.field("dhcpv6.transaction_id"),
                          registrar.field("dhcpv6.hop_count"),
                          registrar.field("dhcpv6.link_address"),
                          registrar.field("dhcpv6.peer_address"),
                          registrar.field("dhcpv6.option"),
                          registrar.field("dhcpv6.option.code"),
                          registrar.field("dhcpv6.option.length"),
                          registrar.field("dhcpv6.option.data"),
                          registrar.field("dhcpv6.duid"),
                          registrar.field("dhcpv6.duid.type"),
                          registrar.field("dhcpv6.duid.hardware_type"),
                          registrar.field("dhcpv6.duid.time"),
                          registrar.field("dhcpv6.duid.enterprise"),
                          registrar.field("dhcpv6.duid.identifier"),
                          registrar.field("dhcpv6.iaid"),
                          registrar.field("dhcpv6.t1"),
                          registrar.field("dhcpv6.t2"),
                          registrar.field("dhcpv6.address"),
                          registrar.field("dhcpv6.preferred_lifetime"),
                          registrar.field("dhcpv6.valid_lifetime"),
                          registrar.field("dhcpv6.prefix_length"),
                          registrar.field("dhcpv6.prefix"),
                          registrar.field("dhcpv6.requested_option"),
                          registrar.field("dhcpv6.preference"),
                          registrar.field("dhcpv6.elapsed_time"),
                          registrar.field("dhcpv6.status_code"),
                          registrar.field("dhcpv6.status_message"),
                          registrar.field("dhcpv6.dns_server"),
                          registrar.field("dhcpv6.domain_search"),
                          registrar.field("dhcpv6.relay_message"),
                          registrar.field("dhcpv6.interface_id"),
                          registrar.field("dhcpv6.rapid_commit"),
                          registrar.field("dhcpv6.information_refresh_time"),
                          registrar.field("dhcpv6.sol_max_rt"),
                          registrar.field("dhcpv6.inf_max_rt"),
                          registrar.field("dhcpv6.trailing"),
                      });
  registrar.bind_udp_port(546, dhcpv6_handle);
  registrar.bind_udp_port(547, dhcpv6_handle);

  registrar.bind_udp_port(
      123, registrar.add_state(
               dissect_ntp, NtpDissectorState{
                                registrar.field("ntp.message"),
                                registrar.field("ntp.flags"),
                                registrar.field("ntp.leap_indicator"),
                                registrar.field("ntp.version"),
                                registrar.field("ntp.mode"),
                                registrar.field("ntp.stratum"),
                                registrar.field("ntp.poll"),
                                registrar.field("ntp.precision"),
                                registrar.field("ntp.root_delay"),
                                registrar.field("ntp.root_dispersion"),
                                registrar.field("ntp.reference_id"),
                                registrar.field("ntp.reference_timestamp"),
                                registrar.field("ntp.origin_timestamp"),
                                registrar.field("ntp.receive_timestamp"),
                                registrar.field("ntp.transmit_timestamp"),
                                registrar.field("ntp.extension"),
                                registrar.field("ntp.extension.type"),
                                registrar.field("ntp.extension.length"),
                                registrar.field("ntp.extension.value"),
                                registrar.field("ntp.key_id"),
                                registrar.field("ntp.digest"),
                                registrar.field("ntp.control.flags"),
                                registrar.field("ntp.control.response"),
                                registrar.field("ntp.control.error"),
                                registrar.field("ntp.control.more"),
                                registrar.field("ntp.control.opcode"),
                                registrar.field("ntp.control.sequence"),
                                registrar.field("ntp.control.status"),
                                registrar.field("ntp.control.association_id"),
                                registrar.field("ntp.control.offset"),
                                registrar.field("ntp.control.count"),
                                registrar.field("ntp.control.data"),
                                registrar.field("ntp.private.flags"),
                                registrar.field("ntp.private.response"),
                                registrar.field("ntp.private.more"),
                                registrar.field("ntp.private.authenticated"),
                                registrar.field("ntp.private.sequence"),
                                registrar.field("ntp.private.implementation"),
                                registrar.field("ntp.private.request_code"),
                                registrar.field("ntp.private.error_code"),
                                registrar.field("ntp.private.item_count"),
                                registrar.field("ntp.private.item_size"),
                                registrar.field("ntp.private.data"),
                                registrar.field("ntp.trailing"),
                            }));
}

} // namespace pruftnet::parsing::internal
